db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://localhost:3306/course_eval_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
db.username=root
db.password=

mail.host=smtp.gmail.com
mail.port=587
mail.username=edhirwa3@gmail.com
mail.password=njcp xwre splm nhyv
